CREATE TABLE USER_TABLE("ID" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 1, increment by 1), "NAME" VARCHAR(255), "DESCRIPTION" VARCHAR(255), "ID_DEPARTMENT" BIGINT)
CREATE TABLE DEPARTMENT_TABLE("ID" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 1, increment by 1), "NAME" VARCHAR(255), "DESCRIPTION" VARCHAR(255))
CREATE TABLE PERMISSION_TABLE("ID" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 1, increment by 1), "NAME" VARCHAR(255), "DESCRIPTION" VARCHAR(255))

INSERT INTO USER_TABLE VALUES (DEFAULT, 'User1', 'Architect', 1)
INSERT INTO USER_TABLE VALUES (DEFAULT, 'User2', 'Mechanic', 2)
INSERT INTO USER_TABLE VALUES (DEFAULT, 'User3', 'Lawyer', 2)
INSERT INTO USER_TABLE VALUES (DEFAULT, 'User4', 'Biologist', 1)
INSERT INTO USER_TABLE VALUES (DEFAULT, 'User5', 'Travel agent', 3)

INSERT INTO DEPARTMENT_TABLE VALUES (DEFAULT, 'Department1', 'This is a description of department1.')
INSERT INTO DEPARTMENT_TABLE VALUES (DEFAULT, 'Department2', 'This is a description of department2.')
INSERT INTO DEPARTMENT_TABLE VALUES (DEFAULT, 'Department3', 'This is a description of department3.')

INSERT INTO PERMISSION_TABLE VALUES (DEFAULT, 'Read', 'This is a description of read permission.')
INSERT INTO PERMISSION_TABLE VALUES (DEFAULT, 'Write', 'This is a description of write permission.')
INSERT INTO PERMISSION_TABLE VALUES (DEFAULT, 'Execute', 'This is a description of execute permission.')